apiVersion: v1
kind: Service
metadata:
  name: loan-service
spec:
  type: NodePort
  selector:
    app: loan-app
  ports:
    - port: 5000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 5000